name: xenforo-thread-analyzer

services:

  xenforo-thread-analyzer:
    container_name: xenforo-thread-analyzer
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    tty: true
    # Copy the pre-commit hook
    command: sh -c 'cp /app/git/hooks/pre-commit /app/.git/hooks/pre-commit && sh'
    volumes:
      - ./:/app
