name: xenforo-thread-analyzer

services:

  xenforo-thread-analyzer:
    container_name: xenforo-thread-analyzer
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    tty: true
    volumes:
      - ./:/app
