# Runs all quality checks in parallel
name: CI

on:
  push:
    branches:
      - main

jobs:

  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          coverage: none

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist

      - name: Run Laravel Pint
        run: vendor/bin/pint --test --ansi

  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          coverage: none

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist

      - name: Run Rector
        run: vendor/bin/rector --dry-run --ansi

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          coverage: none

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan --ansi

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          coverage: xdebug

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
